---
env:
  browser: true
  node: true
  mocha: true
  es6: true
globals:
  "$": true
extends:
  - vizzuality
rules:
  arrow-parens: 0
  camelcase: 0
  comma-dangle: [error, never]
  func-names: 0
  import/extensions: [error, {"js": never, "jsx": never}]
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/prefer-default-export: 0
  jsx-a11y/alt-text: 0
  jsx-a11y/href-no-hash: 0
  max-len: [1, 140, 2, {"ignoreUrls":true}]
  no-console: [error, allow: [warn, error, info]]
  no-mixed-operators: 1
  no-plusplus: ["error", { "allowForLoopAfterthoughts": true }]
  no-underscore-dangle: 0
  no-use-before-define: 0
  object-curly-spacing: 0
  prefer-arrow-callback: 0
  react/forbid-prop-types: 0
  react/jsx-filename-extension: 0
  react/jsx-indent: 1
  react/prefer-stateless-function: 0
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - babel
settings:
  react:
    version: detect
