---
env:
  browser: true
  node: true
  mocha: true
  es6: true
globals:
  "$": true
  Turbolinks: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
rules:
  class-methods-use-this: 0
  import/prefer-default-export: 0
  import/extensions: 0
  import/no-extraneous-dependencies: 0
  import/no-unresolved: 0
  import/named: 0
  react/prefer-stateless-function: 0
  react/jsx-filename-extension: 0
  linebreak-style: 0
  no-plusplus: 0
  jsx-a11y/href-no-hash: 0
  jsx-a11y/anchor-is-valid: 0
  radix: 0
  object-curly-newline: 0
  no-use-before-define: 0
  jsx-a11y/label-has-for: 0
  jsx-a11y/label-has-associated-control:
    - 2
    - assert: either
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - babel
settings:
  import/resolver:
    babel-module: {}
  react:
    version: detect
