AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: leading

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/RescueModifier:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/**/*'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'Gemfile'
    - 'Rakefile'

Metrics:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
