dist: bionic
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
    - /home/travis/.rvm/
services:
  - postgres
addons:
  postgresql: 11
before_install:
  - nvm install
  - node -v
  - npm i -g yarn
install:
  - bundle install --jobs=3 --retry=3
  - yarn
before_script:
  - bundle exec rake db:drop db:create db:schema:load RAILS_ENV=test
script:
  - yarn test
