version: '3.1'

services:

  db:
    image: postgres:11.20-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: laws_and_pathways_development

