aliases:
  "Coal mining (metallurgical)":
    sector: "Coal Mining"
    subsector: "Metallurgical Coal"
  "Coal mining (thermal)":
    sector: "Coal Mining"
    subsector: "Thermal Coal"
  "Electricity Utilities (Global)":
    sector: "Electric Utilities (Global)"
  "Electricity Utilities (Regional)":
    sector: "Electric Utilities (Regional)"

allowlist:
  "Coal Mining":
    - "Metallurgical Coal"
    - "Thermal Coal"

