name: Security

on: push

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Brakeman
        run: yarn test:sast
      - name: Run Bundle Audit
        run: yarn rails:bundle-audit
